  
name: CI

on:
  push:
    branches:
      - development
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        node: ['12.16.2']
        os: [macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g yarn


            
      - run: rm yarn.lock
      - run: yarn
    
      - run: yarn lint
      - run: yarn test
